import 'dart:io';

void main() {
  final file = File('lib/core/localization/app_translations.dart');
  String content = file.readAsStringSync();

  final Map<String, Map<String, String>> newTranslations = {
    'en_US': {
      'create_new_quotation': 'Create New Quotation',
      'edit_quotation': 'Edit Quotation',
      'client_details': 'Client Details',
      'select_client': 'Select Client',
      'client_name_star': 'Client Name *',
      'client_email': 'Client Email',
      'client_address': 'Client Address',
      'client_phone': 'Client Phone',
      'gstin': 'GSTIN',
      'quotation_details': 'Quotation Details',
      'quote_no_star': 'Quote No *',
      'date': 'Date',
      'valid_until': 'Valid Until',
      'place_of_supply': 'Place of Supply',
      'tax_type': 'Tax Type',
      'inclusive': 'Inclusive',
      'exclusive': 'Exclusive',
      'line_items': 'Line Items',
      'add_item': 'Add Item',
      'item_name_title': 'ITEM NAME / TITLE *',
      'desc_optional': 'Description (Optional)',
      'qty': 'Qty',
      'rate': 'Rate',
      'gst': 'GST',
      'amount': 'Amount',
      'financial_summary': 'Financial Summary',
      'subtotal': 'Subtotal',
      'discount_percent': 'Discount (%)',
      'grand_total': 'Grand Total',
      'advance_received': 'Advance Received',
      'balance_due': 'BALANCE DUE',
      'terms_notes': 'Terms & Notes',
      'add_terms_cond': 'Add terms and conditions...',
      'save_quotation': 'Save Quotation',
      'export_pdf': 'Export PDF',
      'share_pdf': 'Share PDF',
      'proposal_for': 'PROPOSAL FOR',
      'valid_until_caps': 'VALID UNTIL',
      'bank_accreditation': 'BANK ACCREDITATION',
      'bank_name_colon': 'Bank Name: ',
      'ac_name_colon': 'A/C Name: ',
      'number_colon': 'Number: ',
      'ifsc_colon': 'IFSC: ',
      'gstin_colon': 'GSTIN: ',
      'proposal': 'PROPOSAL',
      'date_colon': 'Date: ',
      'valid_until_colon': 'Valid Until: ',
      'client_details_caps': 'CLIENT DETAILS',
      'terms_conditions_caps': 'TERMS & CONDITIONS',
      'client': 'CLIENT',
      'quote_no_colon': 'Quote #: ',
      'issued_colon': 'Issued: ',
      'elegant_proposal': 'ELEGANT PROPOSAL',
      'prepared_for': 'PREPARED FOR',
      'proposal_ref_colon': 'Proposal Ref: ',
      'created_on_colon': 'Created On: ',
      'payment_protocol': 'PAYMENT PROTOCOL',
      'beneficiary_colon': 'Beneficiary: ',
      'billed_client': 'BILLED CLIENT',
      'revenue_channel': 'REVENUE CHANNEL',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'AMOUNT IN WORDS',
      'error_req_item': 'At least one item is required',
      'error_req_client': 'Please enter Client Name',
      'error_req_client_export': 'Please enter Client Name before exporting',
      'error_req_quote_no': 'Please enter Proposal/Quotation Number',
      'error_req_item_name': 'Please enter name for Item #',
      'generating_pdf': 'Generating premium Quotation PDF...',
    },
    'hi_IN': {
      'create_new_quotation': 'नया कोटेशन बनाएं',
      'edit_quotation': 'कोटेशन संपादित करें',
      'client_details': 'क्लाइंट विवरण',
      'select_client': 'क्लाइंट चुनें',
      'client_name_star': 'क्लाइंट का नाम *',
      'client_email': 'क्लाइंट ईमेल',
      'client_address': 'क्लाइंट का पता',
      'client_phone': 'क्लाइंट का फोन',
      'gstin': 'जीएसटीिन (GSTIN)',
      'quotation_details': 'कोटेशन विवरण',
      'quote_no_star': 'कोटेशन नंबर *',
      'date': 'तारीख',
      'valid_until': 'वैधता तिथि',
      'place_of_supply': 'आपूर्ति का स्थान',
      'tax_type': 'कर का प्रकार',
      'inclusive': 'सहित (Inclusive)',
      'exclusive': 'रहित (Exclusive)',
      'line_items': 'आइटम सूची',
      'add_item': 'आइटम जोड़ें',
      'item_name_title': 'आइटम का नाम / शीर्षक *',
      'desc_optional': 'विवरण (वैकल्पिक)',
      'qty': 'मात्रा',
      'rate': 'दर',
      'gst': 'जीएसटी',
      'amount': 'रकम',
      'financial_summary': 'वित्तीय सारांश',
      'subtotal': 'उप-योग',
      'discount_percent': 'छूट (%)',
      'grand_total': 'कुल योग',
      'advance_received': 'अग्रिम प्राप्त',
      'balance_due': 'बकाया राशि',
      'terms_notes': 'नियम और नोट्स',
      'add_terms_cond': 'नियम और शर्तें जोड़ें...',
      'save_quotation': 'कोटेशन सहेजें',
      'export_pdf': 'पीडीएफ निर्यात करें',
      'share_pdf': 'पीडीएफ साझा करें',
      'proposal_for': 'के लिए प्रस्ताव',
      'valid_until_caps': 'तक वैध',
      'bank_accreditation': 'बैंक विवरण',
      'bank_name_colon': 'बैंक का नाम: ',
      'ac_name_colon': 'खाता नाम: ',
      'number_colon': 'नंबर: ',
      'ifsc_colon': 'आईएफएससी: ',
      'gstin_colon': 'जीएसटीिन: ',
      'proposal': 'प्रस्ताव',
      'date_colon': 'तारीख: ',
      'valid_until_colon': 'वैधता: ',
      'client_details_caps': 'क्लाइंट विवरण',
      'terms_conditions_caps': 'नियम और शर्तें',
      'client': 'क्लाइंट',
      'quote_no_colon': 'कोटेशन नं: ',
      'issued_colon': 'जारी किया: ',
      'elegant_proposal': 'आकर्षक प्रस्ताव',
      'prepared_for': 'के लिए तैयार',
      'proposal_ref_colon': 'प्रस्ताव संदर्भ: ',
      'created_on_colon': 'बनाया गया: ',
      'payment_protocol': 'भुगतान प्रोटोकॉल',
      'beneficiary_colon': 'लाभार्थी: ',
      'billed_client': 'बिल प्राप्तकर्ता',
      'revenue_channel': 'राजस्व चैनल',
      'ac_colon': 'खाता: ',
      'amount_in_words': 'शब्दों में राशि',
      'error_req_item': 'कम से कम एक आइटम आवश्यक है',
      'error_req_client': 'कृपया क्लाइंट का नाम दर्ज करें',
      'error_req_client_export':
          'निर्यात करने से पहले कृपया क्लाइंट का नाम दर्ज करें',
      'error_req_quote_no': 'कृपया प्रस्ताव/कोटेशन नंबर दर्ज करें',
      'error_req_item_name': 'कृपया आइटम के लिए नाम दर्ज करें #',
      'generating_pdf': 'प्रीमियम कोटेशन पीडीएफ जनरेट हो रहा है...',
    },
    'bn_IN': {
      'create_new_quotation': 'নতুন কোটেশন তৈরি করুন',
      'edit_quotation': 'কোটেশন সম্পাদনা করুন',
      'client_details': 'ক্লায়েন্টের বিবরণ',
      'select_client': 'ক্লায়েন্ট নির্বাচন করুন',
      'client_name_star': 'ক্লায়েন্টের নাম *',
      'client_email': 'ক্লায়েন্ট ইমেইল',
      'client_address': 'ক্লায়েন্টের ঠিকানা',
      'client_phone': 'ক্লায়েন্ট ফোন',
      'gstin': 'জিএসটিআইএন (GSTIN)',
      'quotation_details': 'কোটেশনের বিবরণ',
      'quote_no_star': 'কোটেশন নম্বর *',
      'date': 'তারিখ',
      'valid_until': 'বৈধতা',
      'place_of_supply': 'সরবরাহের স্থান',
      'tax_type': 'করের ধরন',
      'inclusive': 'অন্তর্ভুক্ত',
      'exclusive': 'বহির্ভুক্ত',
      'line_items': 'আইটেম তালিকা',
      'add_item': 'আইটেম যোগ করুন',
      'item_name_title': 'আইটেমের নাম / শিরোনাম *',
      'desc_optional': 'বিবরণ (ঐচ্ছিক)',
      'qty': 'পরিমাণ',
      'rate': 'হার',
      'gst': 'জিএসটি',
      'amount': 'পরিমাণ',
      'financial_summary': 'আর্থিক সারাংশ',
      'subtotal': 'উপ-মোট',
      'discount_percent': 'ছাড় (%)',
      'grand_total': 'সর্বমোট',
      'advance_received': 'অগ্রিম প্রাপ্ত',
      'balance_due': 'বকেয়া',
      'terms_notes': 'শর্তাবলী এবং নোট',
      'add_terms_cond': 'শর্তাবলী যোগ করুন...',
      'save_quotation': 'কোটেশন সংরক্ষণ করুন',
      'export_pdf': 'পিডিএফ এক্সপোর্ট করুন',
      'share_pdf': 'পিডিএফ শেয়ার করুন',
      'proposal_for': 'এর জন্য প্রস্তাব',
      'valid_until_caps': 'পর্যন্ত বৈধ',
      'bank_accreditation': 'ব্যাঙ্কের বিবরণ',
      'bank_name_colon': 'ব্যাঙ্কের নাম: ',
      'ac_name_colon': 'অ্যাকাউন্টের নাম: ',
      'number_colon': 'নম্বর: ',
      'ifsc_colon': 'আইএফএসসি: ',
      'gstin_colon': 'জিএসটিআইএন: ',
      'proposal': 'প্রস্তাব',
      'date_colon': 'তারিখ: ',
      'valid_until_colon': 'বৈধতা: ',
      'client_details_caps': 'ক্লায়েন্টের বিবরণ',
      'terms_conditions_caps': 'শর্তাবলী',
      'client': 'ক্লায়েন্ট',
      'quote_no_colon': 'কোটেশন নং: ',
      'issued_colon': 'জারি করা হয়েছে: ',
      'elegant_proposal': 'আকর্ষণীয় প্রস্তাব',
      'prepared_for': 'এর জন্য প্রস্তুত',
      'proposal_ref_colon': 'প্রস্তাব রেফারেন্স: ',
      'created_on_colon': 'তৈরি করা হয়েছে: ',
      'payment_protocol': 'পেমেন্ট প্রোটোকল',
      'beneficiary_colon': 'উপকারভোগী: ',
      'billed_client': 'বিল করা ক্লায়েন্ট',
      'revenue_channel': 'রাজস্ব চ্যানেল',
      'ac_colon': 'অ্যাকাউন্ট: ',
      'amount_in_words': 'কথায় পরিমাণ',
      'error_req_item': 'অন্তত একটি আইটেম প্রয়োজন',
      'error_req_client': 'দয়া করে ক্লায়েন্টের নাম লিখুন',
      'error_req_client_export':
          'এক্সপোর্ট করার আগে দয়া করে ক্লায়েন্টের নাম লিখুন',
      'error_req_quote_no': 'দয়া করে প্রস্তাব/কোটেশন নম্বর লিখুন',
      'error_req_item_name': 'দয়া করে আইটেমের নাম লিখুন #',
      'generating_pdf': 'প্রিমিয়াম কোটেশন পিডিএফ তৈরি হচ্ছে...',
    },
    'te_IN': {
      'create_new_quotation': 'కొత్త కొటేషన్ సృష్టించండి',
      'edit_quotation': 'కొటేషన్‌ను సవరించండి',
      'client_details': 'క్లయింట్ వివరాలు',
      'select_client': 'క్లయింట్‌ను ఎంచుకోండి',
      'client_name_star': 'క్లయింట్ పేరు *',
      'client_email': 'క్లయింట్ ఇమెయిల్',
      'client_address': 'క్లయింట్ చిరునామా',
      'client_phone': 'క్లయింట్ ఫోన్',
      'gstin': 'జిఎస్టిఐఎన్ (GSTIN)',
      'quotation_details': 'కొటేషన్ వివరాలు',
      'quote_no_star': 'కొటేషన్ నంబర్ *',
      'date': 'తేదీ',
      'valid_until': 'వరకు చెల్లుతుంది',
      'place_of_supply': 'సరఫరా స్థలం',
      'tax_type': 'పన్ను రకం',
      'inclusive': 'కలుపుకొని',
      'exclusive': 'మినహాయించి',
      'line_items': 'అంశాల జాబితా',
      'add_item': 'అంశాన్ని జోడించండి',
      'item_name_title': 'అంశం పేరు / శీర్షిక *',
      'desc_optional': 'వివరణ (ఐచ్ఛికం)',
      'qty': 'పరిమాణం',
      'rate': 'ధర',
      'gst': 'జిఎస్టి',
      'amount': 'మొత్తం',
      'financial_summary': 'ఆర్థిక సారాంశం',
      'subtotal': 'ఉప-మొత్తం',
      'discount_percent': 'తగ్గింపు (%)',
      'grand_total': 'మొత్తం',
      'advance_received': 'ముందుగా స్వీకరించినది',
      'balance_due': 'బాకీ ఉన్నది',
      'terms_notes': 'నిబంధనలు & గమనికలు',
      'add_terms_cond': 'నిబంధనలు మరియు షరతులు జోడించండి...',
      'save_quotation': 'కొటేషన్ సేవ్ చేయండి',
      'export_pdf': 'PDF ఎగుమతి చేయండి',
      'share_pdf': 'PDF భాగస్వామ్యం చేయండి',
      'proposal_for': 'కొరకు ప్రతిపాదన',
      'valid_until_caps': 'వరకు చెల్లుతుంది',
      'bank_accreditation': 'బ్యాంక్ వివరాలు',
      'bank_name_colon': 'బ్యాంకు పేరు: ',
      'ac_name_colon': 'ఖాతా పేరు: ',
      'number_colon': 'నంబర్: ',
      'ifsc_colon': 'IFSC: ',
      'gstin_colon': 'GSTIN: ',
      'proposal': 'ప్రతిపాదన',
      'date_colon': 'తేదీ: ',
      'valid_until_colon': 'చెల్లుబాటు: ',
      'client_details_caps': 'క్లయింట్ వివరాలు',
      'terms_conditions_caps': 'నిబంధనలు & షరతులు',
      'client': 'క్లయింట్',
      'quote_no_colon': 'కోట్ నెం: ',
      'issued_colon': 'జారీ చేయబడింది: ',
      'elegant_proposal': 'సొగసైన ప్రతిపాదన',
      'prepared_for': 'కొరకు సిద్ధం చేయబడింది',
      'proposal_ref_colon': 'ప్రతిపాదన సూచన: ',
      'created_on_colon': 'సృష్టించబడింది: ',
      'payment_protocol': 'చెల్లింపు ప్రోటోకాల్',
      'beneficiary_colon': 'లబ్ధిదారుడు: ',
      'billed_client': 'బిల్ చేయబడిన క్లయింట్',
      'revenue_channel': 'రెవెన్యూ ఛానల్',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'పదాలలో మొత్తం',
      'error_req_item': 'కనీసం ఒక అంశం అవసరం',
      'error_req_client': 'దయచేసి క్లయింట్ పేరును నమోదు చేయండి',
      'error_req_client_export':
          'ఎగుమతి చేయడానికి ముందు దయచేసి క్లయింట్ పేరును నమోదు చేయండి',
      'error_req_quote_no': 'దయచేసి ప్రతిపాదన/కొటేషన్ నంబర్ నమోదు చేయండి',
      'error_req_item_name': 'దయచేసి అంశం పేరును నమోదు చేయండి #',
      'generating_pdf': 'ప్రీమియం కొటేషన్ PDF సృష్టించబడుతోంది...',
    },
    'ta_IN': {
      'create_new_quotation': 'புதிய மேற்கோளை உருவாக்கவும்',
      'edit_quotation': 'மேற்கோளைத் திருத்தவும்',
      'client_details': 'வாடிக்கையாளர் விவரங்கள்',
      'select_client': 'வாடிக்கையாளரைத் தேர்ந்தெடுக்கவும்',
      'client_name_star': 'வாடிக்கையாளர் பெயர் *',
      'client_email': 'வாடிக்கையாளர் மின்னஞ்சல்',
      'client_address': 'வாடிக்கையாளர் முகவரி',
      'client_phone': 'வாடிக்கையாளர் தொலைபேசி',
      'gstin': 'ஜிஎஸ்டிஐஎன் (GSTIN)',
      'quotation_details': 'மேற்கோள் விவரங்கள்',
      'quote_no_star': 'மேற்கோள் எண் *',
      'date': 'தேதி',
      'valid_until': 'இதுவரை செல்லுபடியாகும்',
      'place_of_supply': 'வழங்கும் இடம்',
      'tax_type': 'வரி வகை',
      'inclusive': 'உள்ளடக்கியது',
      'exclusive': 'பிரத்தியேகமானது',
      'line_items': 'பொருட்கள் பட்டியல்',
      'add_item': 'பொருளைச் சேர்',
      'item_name_title': 'பொருளின் பெயர் / தலைப்பு *',
      'desc_optional': 'விளக்கம் (விருப்பத்திற்குரியது)',
      'qty': 'அளவு',
      'rate': 'விலை',
      'gst': 'ஜிஎஸ்டி',
      'amount': 'தொகை',
      'financial_summary': 'நிதி சுருக்கம்',
      'subtotal': 'துணை-மொத்தம்',
      'discount_percent': 'தள்ளுபடி (%)',
      'grand_total': 'பெரு-மொத்தம்',
      'advance_received': 'முன்பணம் பெறப்பட்டது',
      'balance_due': 'நிலுவைத் தொகை',
      'terms_notes': 'விதிமுறைகள் & குறிப்புகள்',
      'add_terms_cond': 'விதிமுறைகள் மற்றும் நிபந்தனைகளைச் சேர்...',
      'save_quotation': 'மேற்கோளைச் சேமி',
      'export_pdf': 'PDF ஏற்றுமதி செய்',
      'share_pdf': 'PDF பகிர்',
      'proposal_for': 'இதற்கான திட்டம்',
      'valid_until_caps': 'இதுவரை செல்லுபடியாகும்',
      'bank_accreditation': 'வங்கி விவரங்கள்',
      'bank_name_colon': 'வங்கி பெயர்: ',
      'ac_name_colon': 'கணக்கு பெயர்: ',
      'number_colon': 'எண்: ',
      'ifsc_colon': 'IFSC: ',
      'gstin_colon': 'GSTIN: ',
      'proposal': 'திட்டம்',
      'date_colon': 'தேதி: ',
      'valid_until_colon': 'செல்லுபடியாகும்: ',
      'client_details_caps': 'வாடிக்கையாளர் விவரங்கள்',
      'terms_conditions_caps': 'விதிமுறைகள் & நிபந்தனைகள்',
      'client': 'வாடிக்கையாளர்',
      'quote_no_colon': 'மேற்கோள் எண்: ',
      'issued_colon': 'வழங்கப்பட்டது: ',
      'elegant_proposal': 'நேர்த்தியான திட்டம்',
      'prepared_for': 'இதற்காக தயாரிக்கப்பட்டது',
      'proposal_ref_colon': 'திட்டக் குறிப்பு: ',
      'created_on_colon': 'உருவாக்கப்பட்டது: ',
      'payment_protocol': 'கட்டண நெறிமுறை',
      'beneficiary_colon': 'பயனாளி: ',
      'billed_client': 'பில் வாடிக்கையாளர்',
      'revenue_channel': 'வருவாய் சேனல்',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'வார்த்தைகளில் தொகை',
      'error_req_item': 'குறைந்தபட்சம் ஒரு பொருள் தேவை',
      'error_req_client': 'வாடிக்கையாளர் பெயரை உள்ளிடவும்',
      'error_req_client_export':
          'ஏற்றுமதி செய்வதற்கு முன் வாடிக்கையாளர் பெயரை உள்ளிடவும்',
      'error_req_quote_no': 'திட்ட/மேற்கோள் எண்ணை உள்ளிடவும்',
      'error_req_item_name': 'பொருளின் பெயரை உள்ளிடவும் #',
      'generating_pdf': 'பிரீமியம் மேற்கோள் PDF உருவாக்கப்படுகிறது...',
    },
    'mr_IN': {
      'create_new_quotation': 'नवीन कोटेशन तयार करा',
      'edit_quotation': 'कोटेशन संपादित करा',
      'client_details': 'क्लायंट तपशील',
      'select_client': 'क्लायंट निवडा',
      'client_name_star': 'क्लायंटचे नाव *',
      'client_email': 'क्लायंट ईमेल',
      'client_address': 'क्लायंटचा पत्ता',
      'client_phone': 'क्लायंट फोन',
      'gstin': 'जीएसटीआयएन (GSTIN)',
      'quotation_details': 'कोटेशन तपशील',
      'quote_no_star': 'कोटेशन क्रमांक *',
      'date': 'तारीख',
      'valid_until': 'पर्यंत वैध',
      'place_of_supply': 'पुरवठ्याचे ठिकाण',
      'tax_type': 'कराचा प्रकार',
      'inclusive': 'सहित',
      'exclusive': 'रहित',
      'line_items': 'आयटम सूची',
      'add_item': 'आयटम जोडा',
      'item_name_title': 'आयटमचे नाव / शीर्षक *',
      'desc_optional': 'वर्णन (पर्यायी)',
      'qty': 'प्रमाण',
      'rate': 'दर',
      'gst': 'जीएसटी',
      'amount': 'रक्कम',
      'financial_summary': 'आर्थिक सारांश',
      'subtotal': 'उप-एकूण',
      'discount_percent': 'सवलत (%)',
      'grand_total': 'एकूण',
      'advance_received': 'आगाऊ रक्कम',
      'balance_due': 'थकबाकी',
      'terms_notes': 'अटी आणि नोट्स',
      'add_terms_cond': 'अटी आणि शर्ती जोडा...',
      'save_quotation': 'कोटेशन सेव्ह करा',
      'export_pdf': 'पीडीएफ निर्यात करा',
      'share_pdf': 'पीडीएफ शेअर करा',
      'proposal_for': 'साठी प्रस्ताव',
      'valid_until_caps': 'पर्यंत वैध',
      'bank_accreditation': 'बँक तपशील',
      'bank_name_colon': 'बँकेचे नाव: ',
      'ac_name_colon': 'खात्याचे नाव: ',
      'number_colon': 'क्रमांक: ',
      'ifsc_colon': 'आयएफएससी: ',
      'gstin_colon': 'जीएसटीआयएन: ',
      'proposal': 'प्रस्ताव',
      'date_colon': 'तारीख: ',
      'valid_until_colon': 'वैधता: ',
      'client_details_caps': 'क्लायंट तपशील',
      'terms_conditions_caps': 'अटी आणि शर्ती',
      'client': 'क्लायंट',
      'quote_no_colon': 'कोटेशन क्र: ',
      'issued_colon': 'जारी केले: ',
      'elegant_proposal': 'आकर्षक प्रस्ताव',
      'prepared_for': 'साठी तयार केले',
      'proposal_ref_colon': 'प्रस्ताव संदर्भ: ',
      'created_on_colon': 'तयार केले: ',
      'payment_protocol': 'पेमेंट प्रोटोकॉल',
      'beneficiary_colon': 'लाभार्थी: ',
      'billed_client': 'बिल क्लायंट',
      'revenue_channel': 'महसूल चॅनेल',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'शब्दांत रक्कम',
      'error_req_item': 'किमान एक आयटम आवश्यक आहे',
      'error_req_client': 'कृपया क्लायंटचे नाव प्रविष्ट करा',
      'error_req_client_export':
          'निर्यात करण्यापूर्वी कृपया क्लायंटचे नाव प्रविष्ट करा',
      'error_req_quote_no': 'कृपया प्रस्ताव/कोटेशन क्रमांक प्रविष्ट करा',
      'error_req_item_name': 'कृपया आयटमसाठी नाव प्रविष्ट करा #',
      'generating_pdf': 'प्रीमियम कोटेशन पीडीएफ जनरेट करत आहे...',
    },
    'gu_IN': {
      'create_new_quotation': 'નવું અવતરણ બનાવો',
      'edit_quotation': 'અવતરણ સંપાદિત કરો',
      'client_details': 'ક્લાયંટની વિગતો',
      'select_client': 'ક્લાયંટ પસંદ કરો',
      'client_name_star': 'ક્લાયંટનું નામ *',
      'client_email': 'ક્લાયંટ ઇમેઇલ',
      'client_address': 'ક્લાયંટ સરનામું',
      'client_phone': 'ક્લાયંટ ફોન',
      'gstin': 'GSTIN',
      'quotation_details': 'અવતરણ વિગતો',
      'quote_no_star': 'અવતરણ નંબર *',
      'date': 'તારીખ',
      'valid_until': 'સુધી માન્ય',
      'place_of_supply': 'સપ્લાયનું સ્થળ',
      'tax_type': 'કરનો પ્રકાર',
      'inclusive': 'સહિત',
      'exclusive': 'બાકાત',
      'line_items': 'આઇટમની સૂચિ',
      'add_item': 'આઇટમ ઉમેરો',
      'item_name_title': 'આઇટમનું નામ / શીર્ષક *',
      'desc_optional': 'વર્ણન (વૈકલ્પિક)',
      'qty': 'જથ્થો',
      'rate': 'દર',
      'gst': 'GST',
      'amount': 'રકમ',
      'financial_summary': 'નાણાકીય સારાંશ',
      'subtotal': 'ઉપ-કુલ',
      'discount_percent': 'ડિસ્કાઉન્ટ (%)',
      'grand_total': 'કુલ',
      'advance_received': 'એડવાન્સ મળેલ',
      'balance_due': 'બાકી રકમ',
      'terms_notes': 'શરતો અને નોંધો',
      'add_terms_cond': 'શરતો અને નિયમો ઉમેરો...',
      'save_quotation': 'અવતરણ સાચવો',
      'export_pdf': 'PDF નિકાસ કરો',
      'share_pdf': 'PDF શેર કરો',
      'proposal_for': 'માટે દરખાસ્ત',
      'valid_until_caps': 'સુધી માન્ય',
      'bank_accreditation': 'બેંક વિગતો',
      'bank_name_colon': 'બેંકનું નામ: ',
      'ac_name_colon': 'ખાતાનું નામ: ',
      'number_colon': 'નંબર: ',
      'ifsc_colon': 'IFSC: ',
      'gstin_colon': 'GSTIN: ',
      'proposal': 'દરખાસ્ત',
      'date_colon': 'તારીખ: ',
      'valid_until_colon': 'માન્યતા: ',
      'client_details_caps': 'ક્લાયંટની વિગતો',
      'terms_conditions_caps': 'શરતો અને નિયમો',
      'client': 'ક્લાયંટ',
      'quote_no_colon': 'અવતરણ નંબર: ',
      'issued_colon': 'ઇશ્યૂ: ',
      'elegant_proposal': 'ભવ્ય દરખાસ્ત',
      'prepared_for': 'માટે તૈયાર',
      'proposal_ref_colon': 'દરખાસ્ત સંદર્ભ: ',
      'created_on_colon': 'બનાવવામાં આવ્યું: ',
      'payment_protocol': 'ચૂકવણી પ્રોટોકોલ',
      'beneficiary_colon': 'લાભાર્થી: ',
      'billed_client': 'બિલ ક્લાયંટ',
      'revenue_channel': 'રેવન્યુ ચેનલ',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'શબ્દોમાં રકમ',
      'error_req_item': 'ઓછામાં ઓછી એક આઇટમ જરૂરી છે',
      'error_req_client': 'કૃપા કરીને ક્લાયંટનું નામ દાખલ કરો',
      'error_req_client_export':
          'નિકાસ કરતા પહેલા કૃપા કરીને ક્લાયંટનું નામ દાખલ કરો',
      'error_req_quote_no': 'કૃપા કરીને દરખાસ્ત/અવતરણ નંબર દાખલ કરો',
      'error_req_item_name': 'કૃપા કરીને આઇટમ માટે નામ દાખલ કરો #',
      'generating_pdf': 'પ્રીમિયમ અવતરણ PDF જનરેટ થઈ રહ્યું છે...',
    },
    'ur_IN': {
      'create_new_quotation': 'نیا کوٹیشن بنائیں',
      'edit_quotation': 'کوٹیشن میں ترمیم کریں',
      'client_details': 'کلائنٹ کی تفصیلات',
      'select_client': 'کلائنٹ منتخب کریں',
      'client_name_star': 'کلائنٹ کا نام *',
      'client_email': 'کلائنٹ کا ای میل',
      'client_address': 'کلائنٹ کا پتہ',
      'client_phone': 'کلائنٹ کا فون',
      'gstin': 'جی ایس ٹی آئی این (GSTIN)',
      'quotation_details': 'کوٹیشن کی تفصیلات',
      'quote_no_star': 'کوٹیشن نمبر *',
      'date': 'تاریخ',
      'valid_until': 'تک درست',
      'place_of_supply': 'فراہمی کی جگہ',
      'tax_type': 'ٹیکس کی قسم',
      'inclusive': 'شامل',
      'exclusive': 'خارج',
      'line_items': 'اشیاء کی فہرست',
      'add_item': 'آئٹم شامل کریں',
      'item_name_title': 'آئٹم کا نام / عنوان *',
      'desc_optional': 'تفصیل (اختیاری)',
      'qty': 'مقدار',
      'rate': 'شرح',
      'gst': 'جی ایس ٹی',
      'amount': 'رقم',
      'financial_summary': 'مالی خلاصہ',
      'subtotal': 'ذیلی کل',
      'discount_percent': 'رعایت (%)',
      'grand_total': 'مجموعی کل',
      'advance_received': 'ایڈوانس موصول',
      'balance_due': 'بقایا جات',
      'terms_notes': 'شرائط اور نوٹس',
      'add_terms_cond': 'شرائط و ضوابط شامل کریں...',
      'save_quotation': 'کوٹیشن محفوظ کریں',
      'export_pdf': 'PDF برآمد کریں',
      'share_pdf': 'PDF شیئر کریں',
      'proposal_for': 'کے لیے تجویز',
      'valid_until_caps': 'تک درست',
      'bank_accreditation': 'بینک کی تفصیلات',
      'bank_name_colon': 'بینک کا نام: ',
      'ac_name_colon': 'اکاؤنٹ کا نام: ',
      'number_colon': 'نمبر: ',
      'ifsc_colon': 'آئی ایف ایس سی: ',
      'gstin_colon': 'جی ایس ٹی آئی این: ',
      'proposal': 'تجویز',
      'date_colon': 'تاریخ: ',
      'valid_until_colon': 'درستگی: ',
      'client_details_caps': 'کلائنٹ کی تفصیلات',
      'terms_conditions_caps': 'شرائط و ضوابط',
      'client': 'کلائنٹ',
      'quote_no_colon': 'کوٹیشن نمبر: ',
      'issued_colon': 'جاری کیا گیا: ',
      'elegant_proposal': 'دلکش تجویز',
      'prepared_for': 'کے لیے تیار کیا گیا',
      'proposal_ref_colon': 'تجویز کا حوالہ: ',
      'created_on_colon': 'بنایا گیا: ',
      'payment_protocol': 'ادائیگی کا پروٹوکول',
      'beneficiary_colon': 'فائدہ اٹھانے والا: ',
      'billed_client': 'بل شدہ کلائنٹ',
      'revenue_channel': 'محصول کا چینل',
      'ac_colon': 'اکاؤنٹ: ',
      'amount_in_words': 'الفاظ میں رقم',
      'error_req_item': 'کم از کم ایک آئٹم درکار ہے',
      'error_req_client': 'براہ کرم کلائنٹ کا نام درج کریں',
      'error_req_client_export':
          'برآمد کرنے سے پہلے براہ کرم کلائنٹ کا نام درج کریں',
      'error_req_quote_no': 'براہ کرم تجویز/کوٹیشن نمبر درج کریں',
      'error_req_item_name': 'براہ کرم آئٹم کا نام درج کریں #',
      'generating_pdf': 'پریمیم کوٹیشن پی ڈی ایف تیار کیا جا رہا ہے...',
    },
    'kn_IN': {
      'create_new_quotation': 'ಹೊಸ ಉದ್ಧರಣವನ್ನು ರಚಿಸಿ',
      'edit_quotation': 'ಉದ್ಧರಣವನ್ನು ಸಂಪಾದಿಸಿ',
      'client_details': 'ಕ್ಲೈಂಟ್ ವಿವರಗಳು',
      'select_client': 'ಕ್ಲೈಂಟ್ ಆಯ್ಕೆಮಾಡಿ',
      'client_name_star': 'ಕ್ಲೈಂಟ್ ಹೆಸರು *',
      'client_email': 'ಕ್ಲೈಂಟ್ ಇಮೇಲ್',
      'client_address': 'ಕ್ಲೈಂಟ್ ವಿಳಾಸ',
      'client_phone': 'ಕ್ಲೈಂಟ್ ಫೋನ್',
      'gstin': 'ಜಿಎಸ್‌ಟಿಐಎನ್ (GSTIN)',
      'quotation_details': 'ಉದ್ಧರಣ ವಿವರಗಳು',
      'quote_no_star': 'ಉದ್ಧರಣ ಸಂಖ್ಯೆ *',
      'date': 'ದಿನಾಂಕ',
      'valid_until': 'ವರೆಗೆ ಮಾನ್ಯ',
      'place_of_supply': 'ಪೂರೈಕೆಯ ಸ್ಥಳ',
      'tax_type': 'ತೆರಿಗೆ ಪ್ರಕಾರ',
      'inclusive': 'ಒಳಗೊಂಡಂತೆ',
      'exclusive': 'ಹೊರತುಪಡಿಸಿ',
      'line_items': 'ಐಟಂ ಪಟ್ಟಿ',
      'add_item': 'ಐಟಂ ಸೇರಿಸಿ',
      'item_name_title': 'ಐಟಂ ಹೆಸರು / ಶೀರ್ಷಿಕೆ *',
      'desc_optional': 'ವಿವರಣೆ (ಐಚ್ಛಿಕ)',
      'qty': 'ಪ್ರಮಾಣ',
      'rate': 'ದರ',
      'gst': 'ಜಿಎಸ್ಟಿ',
      'amount': 'ಮೊತ್ತ',
      'financial_summary': 'ಹಣಕಾಸಿನ ಸಾರಾಂಶ',
      'subtotal': 'ಉಪ-ಮೊತ್ತ',
      'discount_percent': 'ರಿಯಾಯಿತಿ (%)',
      'grand_total': 'ಒಟ್ಟು ಮೊತ್ತ',
      'advance_received': 'ಮುಂಗಡ ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      'balance_due': 'ಬಾಕಿ ಉಳಿದಿದೆ',
      'terms_notes': 'ನಿಯಮಗಳು ಮತ್ತು ಟಿಪ್ಪಣಿಗಳು',
      'add_terms_cond': 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಸೇರಿಸಿ...',
      'save_quotation': 'ಉದ್ಧರಣ ಉಳಿಸಿ',
      'export_pdf': 'ಪಿಡಿಎಫ್ ರಫ್ತು ಮಾಡಿ',
      'share_pdf': 'ಪಿಡಿಎಫ್ ಹಂಚಿಕೊಳ್ಳಿ',
      'proposal_for': 'ಗಾಗಿ ಪ್ರಸ್ತಾವನೆ',
      'valid_until_caps': 'ವರೆಗೆ ಮಾನ್ಯ',
      'bank_accreditation': 'ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
      'bank_name_colon': 'ಬ್ಯಾಂಕ್ ಹೆಸರು: ',
      'ac_name_colon': 'ಖಾತೆ ಹೆಸರು: ',
      'number_colon': 'ಸಂಖ್ಯೆ: ',
      'ifsc_colon': 'ಐಎಫ್‌ಎಸ್‌ಸಿ: ',
      'gstin_colon': 'ಜಿಎಸ್‌ಟಿಐಎನ್: ',
      'proposal': 'ಪ್ರಸ್ತಾವನೆ',
      'date_colon': 'ದಿನಾಂಕ: ',
      'valid_until_colon': 'ಮಾನ್ಯತೆ: ',
      'client_details_caps': 'ಕ್ಲೈಂಟ್ ವಿವರಗಳು',
      'terms_conditions_caps': 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
      'client': 'ಕ್ಲೈಂಟ್',
      'quote_no_colon': 'ಉದ್ಧರಣ ನಂ: ',
      'issued_colon': 'ನೀಡಲಾಗಿದೆ: ',
      'elegant_proposal': 'ಆಕರ್ಷಕ ಪ್ರಸ್ತಾವನೆ',
      'prepared_for': 'ಗಾಗಿ ಸಿದ್ಧಪಡಿಸಲಾಗಿದೆ',
      'proposal_ref_colon': 'ಪ್ರಸ್ತಾವನೆ ಉಲ್ಲೇಖ: ',
      'created_on_colon': 'ರಚಿಸಲಾಗಿದೆ: ',
      'payment_protocol': 'ಪಾವತಿ ಪ್ರೋಟೋಕಾಲ್',
      'beneficiary_colon': 'ಫಲಾನುಭವಿ: ',
      'billed_client': 'ಬಿಲ್ಡ್ ಕ್ಲೈಂಟ್',
      'revenue_channel': 'ಆದಾಯ ಚಾನಲ್',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'ಪದಗಳಲ್ಲಿ ಮೊತ್ತ',
      'error_req_item': 'ಕನಿಷ್ಠ ಒಂದು ಐಟಂ ಅಗತ್ಯವಿದೆ',
      'error_req_client': 'ದಯವಿಟ್ಟು ಕ್ಲೈಂಟ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'error_req_client_export':
          'ರಫ್ತು ಮಾಡುವ ಮೊದಲು ದಯವಿಟ್ಟು ಕ್ಲೈಂಟ್ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
      'error_req_quote_no': 'ದಯವಿಟ್ಟು ಪ್ರಸ್ತಾವನೆ/ಉದ್ಧರಣ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'error_req_item_name': 'ದಯವಿಟ್ಟು ಐಟಂ ಹೆಸರನ್ನು ನಮೂದಿಸಿ #',
      'generating_pdf': 'ಪ್ರೀಮಿಯಂ ಉದ್ಧರಣ ಪಿಡಿಎಫ್ ಅನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    },
    'or_IN': {
      'create_new_quotation': 'ନୂଆ କୋଟେସନ୍ ତିଆରି କରନ୍ତୁ',
      'edit_quotation': 'କୋଟେସନ୍ ସମ୍ପାଦନା କରନ୍ତୁ',
      'client_details': 'କ୍ଲାଏଣ୍ଟ ବିବରଣୀ',
      'select_client': 'କ୍ଲାଏଣ୍ଟ ଚୟନ କରନ୍ତୁ',
      'client_name_star': 'କ୍ଲାଏଣ୍ଟର ନାମ *',
      'client_email': 'କ୍ଲାଏଣ୍ଟର ଇମେଲ୍',
      'client_address': 'କ୍ଲାଏଣ୍ଟର ଠିକଣା',
      'client_phone': 'କ୍ଲାଏଣ୍ଟ ଫୋନ୍',
      'gstin': 'ଜିଏସଟିଆଇଏନ୍ (GSTIN)',
      'quotation_details': 'କୋଟେସନ୍ ବିବରଣୀ',
      'quote_no_star': 'କୋଟେସନ୍ ନମ୍ବର *',
      'date': 'ତାରିଖ',
      'valid_until': 'ପର୍ଯ୍ୟନ୍ତ ବୈଧ',
      'place_of_supply': 'ଯୋଗାଣ ସ୍ଥାନ',
      'tax_type': 'ଟ୍ୟାକ୍ସ ପ୍ରକାର',
      'inclusive': 'ଅନ୍ତର୍ଭୁକ୍ତ',
      'exclusive': 'ବାଦ୍ ଦିଆଯାଇଛି',
      'line_items': 'ଆଇଟମ୍ ତାଲିକା',
      'add_item': 'ଆଇଟମ୍ ଯୋଡନ୍ତୁ',
      'item_name_title': 'ଆଇଟମ୍ ନାମ / ଶୀର୍ଷକ *',
      'desc_optional': 'ବିବରଣୀ (ବୈକଳ୍ପିକ)',
      'qty': 'ପରିମାଣ',
      'rate': 'ହାର',
      'gst': 'ଜିଏସଟି',
      'amount': 'ପରିମାଣ',
      'financial_summary': 'ଆର୍ଥିକ ସାରାଂଶ',
      'subtotal': 'ଉପ-ମୋଟ',
      'discount_percent': 'ରିହାତି (%)',
      'grand_total': 'ମୋଟ ପରିମାଣ',
      'advance_received': 'ଅଗ୍ରୀମ ପ୍ରାପ୍ତ',
      'balance_due': 'ବକେୟା',
      'terms_notes': 'ସର୍ତ୍ତାବଳୀ ଏବଂ ନୋଟ୍',
      'add_terms_cond': 'ସର୍ତ୍ତାବଳୀ ଯୋଡନ୍ତୁ...',
      'save_quotation': 'କୋଟେସନ୍ ସେଭ୍ କରନ୍ତୁ',
      'export_pdf': 'ପିଡିଏଫ୍ ଏକ୍ସପୋର୍ଟ କରନ୍ତୁ',
      'share_pdf': 'ପିଡିଏଫ୍ ସେୟାର୍ କରନ୍ତୁ',
      'proposal_for': 'ପାଇଁ ପ୍ରସ୍ତାବ',
      'valid_until_caps': 'ପର୍ଯ୍ୟନ୍ତ ବୈଧ',
      'bank_accreditation': 'ବ୍ୟାଙ୍କ ବିବରଣୀ',
      'bank_name_colon': 'ବ୍ୟାଙ୍କ ନାମ: ',
      'ac_name_colon': 'ଆକାଉଣ୍ଟ ନାମ: ',
      'number_colon': 'ନମ୍ବର: ',
      'ifsc_colon': 'ଆଇଏଫଏସସି: ',
      'gstin_colon': 'ଜିଏସଟିଆଇଏନ୍: ',
      'proposal': 'ପ୍ରସ୍ତାବ',
      'date_colon': 'ତାରିଖ: ',
      'valid_until_colon': 'ବୈଧତା: ',
      'client_details_caps': 'କ୍ଲାଏଣ୍ଟ ବିବରଣୀ',
      'terms_conditions_caps': 'ସର୍ତ୍ତାବଳୀ',
      'client': 'କ୍ଲାଏଣ୍ଟ',
      'quote_no_colon': 'କୋଟେସନ୍ ନମ୍ବର: ',
      'issued_colon': 'ଜାରି କରାଯାଇଛି: ',
      'elegant_proposal': 'ଆକର୍ଷଣୀୟ ପ୍ରସ୍ତାବ',
      'prepared_for': 'ପାଇଁ ପ୍ରସ୍ତୁତ',
      'proposal_ref_colon': 'ପ୍ରସ୍ତାବ ସନ୍ଦର୍ଭ: ',
      'created_on_colon': 'ତିଆରି କରାଯାଇଛି: ',
      'payment_protocol': 'ପେମେଣ୍ଟ ପ୍ରୋଟୋକଲ୍',
      'beneficiary_colon': 'ହିତାଧିକାରୀ: ',
      'billed_client': 'ବିଲ୍ କ୍ଲାଏଣ୍ଟ',
      'revenue_channel': 'ରାଜସ୍ୱ ଚ୍ୟାନେଲ୍',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'ଶବ୍ଦରେ ପରିମାଣ',
      'error_req_item': 'ଅତିକମରେ ଗୋଟିଏ ଆଇଟମ୍ ଆବଶ୍ୟକ',
      'error_req_client': 'ଦୟାକରି କ୍ଲାଏଣ୍ଟର ନାମ ପ୍ରବେଶ କରନ୍ତୁ',
      'error_req_client_export':
          'ଏକ୍ସପୋର୍ଟ କରିବା ପୂର୍ବରୁ ଦୟାକରି କ୍ଲାଏଣ୍ଟର ନାମ ପ୍ରବେଶ କରନ୍ତୁ',
      'error_req_quote_no': 'ଦୟାକରି ପ୍ରସ୍ତାବ/କୋଟେସନ୍ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
      'error_req_item_name': 'ଦୟାକରି ଆଇଟମ୍ ନାମ ପ୍ରବେଶ କରନ୍ତୁ #',
      'generating_pdf': 'ପ୍ରିମିୟମ୍ କୋଟେସନ୍ ପିଡିଏଫ୍ ତିଆରି ହେଉଛି...',
    },
    'ml_IN': {
      'create_new_quotation': 'പുതിയ കൊട്ടേഷൻ ഉണ്ടാക്കുക',
      'edit_quotation': 'കൊട്ടേഷൻ തിരുത്തുക',
      'client_details': 'ക്ലയന്റ് വിശദാംശങ്ങൾ',
      'select_client': 'ക്ലയന്റിനെ തിരഞ്ഞെടുക്കുക',
      'client_name_star': 'ക്ലയന്റ് പേര് *',
      'client_email': 'ക്ലയന്റ് ഇമെയിൽ',
      'client_address': 'ക്ലയന്റ് വിലാസം',
      'client_phone': 'ക്ലയന്റ് ഫോൺ',
      'gstin': 'ജിഎസ്ടിഐഎൻ (GSTIN)',
      'quotation_details': 'കൊട്ടേഷൻ വിശദാംശങ്ങൾ',
      'quote_no_star': 'കൊട്ടേഷൻ നമ്പർ *',
      'date': 'തീയതി',
      'valid_until': 'ഇതുവരെ സാധുതയുണ്ട്',
      'place_of_supply': 'വിതരണ സ്ഥലം',
      'tax_type': 'നികുതി തരം',
      'inclusive': 'ഉൾപ്പെടെയുള്ള',
      'exclusive': 'ഒഴിവാക്കിയുള്ള',
      'line_items': 'ഇനങ്ങളുടെ പട്ടിക',
      'add_item': 'ഇനം ചേർക്കുക',
      'item_name_title': 'ഇനത്തിന്റെ പേര് / തലക്കെട്ട് *',
      'desc_optional': 'വിവരണം (ഓപ്ഷണൽ)',
      'qty': 'അളവ്',
      'rate': 'നിരക്ക്',
      'gst': 'ജിഎസ്ടി',
      'amount': 'തുക',
      'financial_summary': 'സാമ്പത്തിക സംഗ്രഹം',
      'subtotal': 'ഉപ-ആകെത്തുക',
      'discount_percent': 'കിഴിവ് (%)',
      'grand_total': 'ആകെത്തുക',
      'advance_received': 'അഡ്വാൻസ് ലഭിച്ചു',
      'balance_due': 'ബാക്കി തുക',
      'terms_notes': 'നിബന്ധനകളും കുറിപ്പുകളും',
      'add_terms_cond': 'നിബന്ധനകളും വ്യവസ്ഥകളും ചേർക്കുക...',
      'save_quotation': 'കൊട്ടേഷൻ സേവ് ചെയ്യുക',
      'export_pdf': 'PDF എക്സ്പോർട്ട് ചെയ്യുക',
      'share_pdf': 'PDF പങ്കിടുക',
      'proposal_for': 'ഇതിനായുള്ള നിർദ്ദേശം',
      'valid_until_caps': 'ഇതുവരെ സാധുതയുണ്ട്',
      'bank_accreditation': 'ബാങ്ക് വിവരങ്ങൾ',
      'bank_name_colon': 'ബാങ്ക് പേര്: ',
      'ac_name_colon': 'അക്കൗണ്ട് പേര്: ',
      'number_colon': 'നമ്പർ: ',
      'ifsc_colon': 'IFSC: ',
      'gstin_colon': 'GSTIN: ',
      'proposal': 'നിർദ്ദേശം',
      'date_colon': 'തീയതി: ',
      'valid_until_colon': 'സാധുത: ',
      'client_details_caps': 'ക്ലയന്റ് വിശദാംശങ്ങൾ',
      'terms_conditions_caps': 'നിബന്ധനകളും വ്യവസ്ഥകളും',
      'client': 'ക്ലയന്റ്',
      'quote_no_colon': 'കൊട്ടേഷൻ നമ്പർ: ',
      'issued_colon': 'നൽകിയത്: ',
      'elegant_proposal': 'മനോഹരമായ നിർദ്ദേശം',
      'prepared_for': 'ഇതിനായി തയ്യാറാക്കിയത്',
      'proposal_ref_colon': 'നിർദ്ദേശ റഫറൻസ്: ',
      'created_on_colon': 'സൃഷ്ടിച്ചത്: ',
      'payment_protocol': 'പേയ്‌മെന്റ് പ്രോട്ടോക്കോൾ',
      'beneficiary_colon': 'ഗുണഭോക്താവ്: ',
      'billed_client': 'ബിൽ ക്ലയന്റ്',
      'revenue_channel': 'വരുമാന ചാനൽ',
      'ac_colon': 'A/C: ',
      'amount_in_words': 'വാക്കുകളിൽ തുക',
      'error_req_item': 'കുറഞ്ഞത് ഒരു ഇനമെങ്കിലും ആവശ്യമാണ്',
      'error_req_client': 'ദയവായി ക്ലയന്റ് പേര് നൽകുക',
      'error_req_client_export':
          'എക്സ്പോർട്ട് ചെയ്യുന്നതിന് മുമ്പ് ദയവായി ക്ലയന്റ് പേര് നൽകുക',
      'error_req_quote_no': 'ദയവായി നിർദ്ദേശം/കൊട്ടേഷൻ നമ്പർ നൽകുക',
      'error_req_item_name': 'ദയവായി ഇനത്തിന്റെ പേര് നൽകുക #',
      'generating_pdf': 'പ്രീമിയം കൊട്ടേഷൻ PDF സൃഷ്ടിക്കുന്നു...',
    },
  };

  for (var entry in newTranslations.entries) {
    final locale = entry.key;
    final dict = entry.value;

    final startIndex = content.indexOf("'\$locale': {");
    if (startIndex == -1) continue;

    int endIndex = content.indexOf("},", startIndex);
    if (endIndex == -1) endIndex = content.lastIndexOf("}");

    String localeBlock = content.substring(startIndex, endIndex);

    for (var key in dict.keys) {
      if (!localeBlock.contains("'\$key':")) {
        localeBlock += "\n          '\$key': '\${dict[key]}',";
      }
    }

    content = content.replaceRange(startIndex, endIndex, localeBlock);
  }

  file.writeAsStringSync(content);
  print('Injected quotations translations into app_translations.dart!');
}
