// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdkgkTy2LKXJD3iRZwvmrcIUYZczNrsQw',
    appId: '1:819064312384:web:aa4bfea5c0ee98100d85a5',
    messagingSenderId: '819064312384',
    projectId: 'aurivabms-app',
    authDomain: 'aurivabms-app.firebaseapp.com',
    storageBucket: 'aurivabms-app.firebasestorage.app',
    measurementId: 'G-QJ7Y3BE07M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9pBlwCMo0y2PWoJQPrKBHrKcX47Urtf8',
    appId: '1:819064312384:android:f68b194079f5c0d30d85a5',
    messagingSenderId: '819064312384',
    projectId: 'aurivabms-app',
    storageBucket: 'aurivabms-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8T6YA99mDr7DIvK8BXeOMNHqYTUQO_Y4',
    appId: '1:819064312384:ios:1e29e7864901e9820d85a5',
    messagingSenderId: '819064312384',
    projectId: 'aurivabms-app',
    storageBucket: 'aurivabms-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
}
